export const CONTENT = Object.freeze({
  GET_ARTICLES_REQUEST: 'CONTENT_GET_ARTICLES_REQUEST',
  GET_ARTICLES_SUCCESS: 'CONTENT_GET_ARTICLES_SUCCESS',
  GET_ARTICLES_FAILURE: 'CONTENT_GET_ARTICLES_FAILURE',

  GET_FROM_CATEGORY_REQUEST: 'GET_GET_FROM_CATEGORY_REQUEST',
  GET_FROM_CATEGORY_SUCCESS: 'CONTENT_GET_FROM_CATEGORY_SUCCESS',
  GET_FROM_CATEGORY_FAILURE: 'CONTENT_GET_FROM_CATEGORY_FAILURE',

  GET_FROM_SEARCH_REQUEST: 'GET_GET_FROM_SEARCH_REQUEST',
  GET_FROM_SEARCH_SUCCESS: 'CONTENT_GET_FROM_SEARCH_SUCCESS',
  GET_FROM_SEARCH_FAILURE: 'CONTENT_GET_FROM_SEARCH_FAILURE'
});

export const AUTH = Object.freeze({
  SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'AUTH_SIGN_IN_FAILURE',

  SIGN_OUT_REQUEST: 'AUTH_SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'AUTH_SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'AUTH_SIGN_OUT_FAILURE',

  SIGN_UP_REQUEST: 'AUTH_SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'AUTH_SIGN_UP_FAILURE'
});
